//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steve.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steve.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edmzkxfoprcnhijtyvl
        ///adxntojykfcvzermplh
        ///
        ///jbhpksufcaty
        ///hevsuaibjkt
        ///jbusytghak
        ///
        ///ixpckvbrylgtdm
        ///hpyojlsgibtvc
        ///
        ///sga
        ///sag
        ///gsra
        ///awzgs
        ///sga
        ///
        ///jnwcqfisokbgmt
        ///jmtcubwnsk
        ///bmwkctjsrn
        ///
        ///ekxwotiyfhagdlmqn
        ///hpvedxwscgqjlkrf
        ///
        ///drtguxboe
        ///uxotwejgibfdrn
        ///rkgxbtaeoupd
        ///kohedbgzurtx
        ///
        ///di
        ///whdg
        ///d
        ///d
        ///
        ///pukeyxjrvmowta
        ///ejyxrwopkhtu
        ///upojtrxyekw
        ///cjxubkyetrowp
        ///tgxwyorqnejiufzkp
        ///
        ///nqbraty
        ///ybrqna
        ///qyanbr
        ///ayrqbn
        ///aynqbr
        ///
        ///ezljbkmhionfqv
        ///hxvtnjqr
        ///
        ///fuwsngzivcjrk
        ///kprjnfucziv
        ///
        ///wonvukgls
        ///wkoslgvun
        ///kusvto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayFour {
            get {
                return ResourceManager.GetString("DayFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 939
        ///7,13,x,x,59,x,31,19.
        /// </summary>
        internal static string DayThirteen {
            get {
                return ResourceManager.GetString("DayThirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N1
        ///S4
        ///L180
        ///W5
        ///S5
        ///E2
        ///N3
        ///N5
        ///E5
        ///F25
        ///S5
        ///F88
        ///L90
        ///F8
        ///R90
        ///E2
        ///L90
        ///F72
        ///S2
        ///E2
        ///F82
        ///N1
        ///W4
        ///R90
        ///W3
        ///F29
        ///L90
        ///E2
        ///L90
        ///W5
        ///L90
        ///F82
        ///R90
        ///F36
        ///R180
        ///F19
        ///W4
        ///F40
        ///W1
        ///R270
        ///E5
        ///N3
        ///W5
        ///E5
        ///L90
        ///E4
        ///R90
        ///F50
        ///E1
        ///W2
        ///R180
        ///N3
        ///W2
        ///S4
        ///F33
        ///W1
        ///L90
        ///W3
        ///R90
        ///F51
        ///R270
        ///E3
        ///R90
        ///W5
        ///S4
        ///F72
        ///R90
        ///S4
        ///E3
        ///F66
        ///R270
        ///S3
        ///E4
        ///L90
        ///E2
        ///R90
        ///F94
        ///L90
        ///F19
        ///W2
        ///L90
        ///F68
        ///N2
        ///S3
        ///F40
        ///W3
        ///F47
        ///S5
        ///W1
        ///R90
        ///F38
        ///L180
        ///F70
        ///N2
        ///L90
        ///F13
        ///R270
        ///F57
        ///E2
        ///R90
        ///N5
        ///L90
        ///F54
        ///W3
        ///S2
        ///F27
        ///S3
        ///E2
        ///S2
        ///F29
        ///F8
        ///S5
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayTwelve {
            get {
                return ResourceManager.GetString("DayTwelve", resourceCulture);
            }
        }
    }
}
